Feat: Improve error handling
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/json-key-value-lookup-action/action.yaml b/.github/actions/json-key-value-lookup-action/action.yaml
--- a/.github/actions/json-key-value-lookup-action/action.yaml
+++ b/.github/actions/json-key-value-lookup-action/action.yaml
@@ -13,6 +13,11 @@ inputs:
     description: "The JSON key requiring lookup"
     type: string
     required: true
+  DEFAULT:
+    # Can be used to prevent exit/error if lookup fails
+    description: "Default value to return if lookup fails"
+    type: string
+    required: false
 
 outputs:
   VALUE:
@@ -27,31 +32,48 @@ runs:
       shell: bash
       run: |
         # JSON Variable Key/Value Lookup
-        echo "### 🔑 JSON Variable Key/Value Lookup" >> "$GITHUB_STEP_SUMMARY"
 
+        echo "### 🔑 JSON Variable Key/Value Lookup" >> "$GITHUB_STEP_SUMMARY"
         JSON="${{ inputs.json }}"
-        # Validate the variable is not empty/unset
+        KEY="${{ inputs.KEY }}"
+
+        # Validate that input variables are populated
         if [ -z "$JSON" ]; then
-          echo "The required lookup variable/JSON was NOT passed as input ❌"
+          echo "Error: the required variable/JSON string was NOT passed as input ❌"; exit 1
+        elif [ -z "$KEY" ]; then
+          echo "Error: the required key to lookup was NOT passed as input ❌"; exit 1
+        fi
+
+        # Ensure JSON parser/binary is available
+        JQ=$(which jq || true)
+        if [ ! -x "$JQ" ]; then
+          echo "Error: jq command was NOT found in the PATH"
           exit 1
         fi
 
-        echo "Key to lookup: ${{ inputs.key }} 🔑"
-
-        JQ=$(which jq || true)
-        if [ -x "$JQ" ]; then
-          KEY="${{ inputs.KEY }}"
-
-          VALUE=$(echo '${{ inputs.JSON }}' | \
-            jq -r --arg KEY "$KEY" '.[] | select(.key==$KEY) | .value')
-
-          if [ -z "$VALUE" ]; then
-            echo "Key/value lookup failed ❌"; exit 1
-          fi
-          echo "Value returned: $VALUE 💬"
+        # Check that string parses as valid JSON
+        if (jq -re '""' <<<" ${JSON}" 2>&1)
+          echo "JSON parsing successful ✅"
         else
-          echo "Error: jq command was NOT found in the PATH"; exit 1
+          echo "Error: jq command was NOT able to parse JSON ❌"; exit 1
         fi
+
+        echo "Key to lookup: $KEY 🔑"
+
+        # VALUE=$(echo '${{ inputs.JSON }}' | \
+
+        VALUE=$(echo '$JSON' | \
+          jq -r --arg KEY "$KEY" '.[] | select(.key==$KEY) | .value')
+
+        if [ -z "$VALUE" ] && [ -z "$DEFAULT" ]; then
+          # If no default return value provided, throw a fatal error
+          echo "Key/value lookup failed ❌"; exit 1
+        elif [ -z "$VALUE" ]; then
+          echo "Key/value lookup failed ⚠️"
+          VALUE="${{ inputs.default }}"
+        fi
+
+        echo "Returning value: $VALUE 💬"
         echo "value=$VALUE" >> "$GITHUB_ENV"
         echo "value=$VALUE" >> "$GITHUB_OUTPUT"
         echo "Key to lookup: ${{ inputs.key }}" >> "$GITHUB_STEP_SUMMARY"
