Fix: Missing then in flow control statement
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/json-key-value-lookup-action/action.yaml b/.github/actions/json-key-value-lookup-action/action.yaml
--- a/.github/actions/json-key-value-lookup-action/action.yaml
+++ b/.github/actions/json-key-value-lookup-action/action.yaml
@@ -47,12 +47,11 @@ runs:
         # Ensure JSON parser/binary is available
         JQ=$(which jq || true)
         if [ ! -x "$JQ" ]; then
-          echo "Error: jq command was NOT found in the PATH"
-          exit 1
+          echo "Error: jq command was NOT found in the PATH ❌"; exit 1
         fi
 
         # Check that string parses as valid JSON
-        if (jq -re '""' <<<" ${JSON}" 2>&1)
+        if (jq -re '""' <<<" ${JSON}" 2>&1); then
           echo "JSON parsing successful ✅"
         else
           echo "Error: jq command was NOT able to parse JSON ❌"; exit 1
@@ -61,7 +60,6 @@ runs:
         echo "Key to lookup: $KEY 🔑"
 
         # VALUE=$(echo '${{ inputs.JSON }}' | \
-
         VALUE=$(echo '$JSON' | \
           jq -r --arg KEY "$KEY" '.[] | select(.key==$KEY) | .value')
 
